# Generated by Django 5.2.5 on 2025-08-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50, verbose_name='操作IP')),
                ('database_name', models.CharField(max_length=100, verbose_name='目标数据库')),
                ('table_name', models.CharField(max_length=100, verbose_name='目标表名')),
                ('generation_count', models.IntegerField(verbose_name='生成数量')),
                ('start_date', models.CharField(max_length=20, verbose_name='开始日期')),
                ('end_date', models.CharField(max_length=20, verbose_name='结束日期')),
                ('generation_rules', models.TextField(verbose_name='造数规则')),
                ('operation_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('status', models.BooleanField(default=True, verbose_name='操作状态')),
                ('error_msg', models.TextField(blank=True, null=True, verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '数据生成日志',
                'verbose_name_plural': '数据生成日志',
                'ordering': ['-operation_time'],
            },
        ),
    ]
